# 389. Find the Difference
# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

from collections import defaultdict


def findTheDifference(s, t):
    map = defaultdict(int)
    for i in range(len(t)):
        map[t[i]] += 1

    for i in range(len(s)):
        map[s[i]] -= 1

    for k, v in map.items():
        if v > 0:
            return k


print(findTheDifference("abcd", "abcde"))  # "e"
